version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /your/path/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={YOUR_PASSWORD}
      - MYSQL_PASSWORD={YOUR_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 5000:80
    links:
      - db
    volumes:
      - /your/path/nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD={YOUR_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db